### ISSUE TITLE
Using tact.vim within Nvim

### ISSUE THREAD

**Issue by mbaneshi** [tact-lang/tact.vim#1]
Hi there,  

 
Would you please update README and show instruction for setup it up in Nvim,
specifically by modern package manager like Lazyvim.  

Thank you in advance.

**Comment by novusnota** [comment]
Added in [this commit](https://github.com/tact-lang/tact.vim/commit/d8a4a8036beff3eda8f96d31d23dcb21383150eb):

- Setup instructions for `tact.vim` in Neovim using [lazy.nvim](https://github.com/folke/lazy.nvim)
- Neovim-specific Lua configuration variants for every existing VimScript/Vim option

Notice, however, that none of the Lua setup is necessary in Neovim as everything can be done the same way as in Vim by using VimScript and existing package manager, including the built-in one in Neovim.
