### ISSUE TITLE
Idea: Use of tree-sitter-tact or Ohm's grammar

### ISSUE THREAD

**Issue by novusnota** [tact-lang/tact.vim#10]
This may help with inference, and thus would remove most of the dirty regex work.

UPD: It should be really done in LSP, then re-used here alongside with the current options (which may then be called "legacy")

**Comment by anton-trunov** [comment]
That would be awesome!

**Comment by novusnota** [comment]
At the moment the idea is not very feasible as Vim Script has very poor FFI and it cannot bind. Additionally, calling Node.js scripts in the background provides a substantial overhead, which makes it only usable as a debounceable background diagnostic tool and a build tool (#11).

Therefore, neither Ohm from Tact's compiler nor Tree-sitter would or could replace the current RegExp-based logic of the plugin. However, this will: #26
